#!/usr/bin/env bash
# Check that Cobbler can add and remove systems

source ${SYSTESTS_PRELUDE} && prepare

set -x -e -o pipefail

cobbler distro add --name fake --arch x86_64 --kernel ${fake_kernel} \
	--initrd ${fake_initramfs}
cobbler profile add --name fake --distro fake
cobbler system add --name testbed-${i} --profile fake

# Act
cobbler system edit --name test --netboot-enabled 1 --enable-ipxe 1

# Assert

